# All synthetic. Fictional "ExampleBank"; reserved example domains only.
EXAMPLES = [
 dict(id="phish", label="Synthetic: account suspension phishing", sender="support@examplebank-alerts.example.net", message_type="email",
      message="URGENT: Your ExampleBank account will be suspended within 24 hours. Verify your password at http://examplebank-secure.example.net/login now.",
      expected_levels=["High", "Critical"], expected_rules=["CRED_REQUEST", "URGENCY_THREAT", "URL_BRAND_MISMATCH"], why="Credential request + deadline + brand/domain mismatch."),
 dict(id="otp", label="Synthetic: OTP scam", sender=None, message_type="sms",
      message="Dear customer, your account is locked. Reply with the OTP sent to your phone immediately to unlock.",
      expected_levels=["Medium", "High", "Critical"], expected_rules=["CRED_REQUEST", "URGENCY_THREAT"], why="OTP solicitation combined with urgency."),
 dict(id="payment", label="Synthetic: payment impersonation", sender=None, message_type="email",
      message="Hi, this is the CEO. We changed our bank details. Please wire $4,800 today to the new account and keep this confidential.",
      expected_levels=["Medium", "High"], expected_rules=["PAY_CHANGED_BANK", "CTX_BYPASS_VERIFICATION"], why="Changed bank details, urgent transfer, secrecy."),
 dict(id="reward", label="Synthetic: fake reward", sender=None, message_type="sms",
      message="Congratulations! You won a $500 prize. Pay a $20 processing fee in gift cards to claim it.",
      expected_levels=["Medium", "High"], expected_rules=["REWARD_UNEXPECTED", "PAY_GIFTCARD_CRYPTO"], why="Prize plus gift-card fee."),
 dict(id="college", label="Synthetic: benign college announcement", sender="office@college.example.edu", message_type="email",
      message="The library will be closed on Monday for maintenance. Classes resume Tuesday as normal.",
      expected_levels=["Low"], expected_rules=[], why="Ordinary notice; should score low."),
 dict(id="delivery", label="Synthetic: benign delivery update", sender=None, message_type="sms",
      message="Your package was delivered to the front desk at 2 PM. No action needed.",
      expected_levels=["Low"], expected_rules=[], why="No link, no request."),
 dict(id="alert", label="Synthetic: ambiguous security alert", sender=None, message_type="email",
      message="Security alert: new sign-in to your account from a new device. If this wasn't you, review activity in the official app.",
      expected_levels=["Low"], expected_rules=[], why="Legitimate-looking but unverifiable; should be Inconclusive, not 'safe'."),
 dict(id="impersonation", label="Synthetic: fictional-brand impersonation", sender="help@examplebank-support.example.org", message_type="email",
      message="ExampleBank Support: please review your recent activity at http://examplebank-login.example.org/verify",
      expected_levels=["Low", "Medium"], expected_rules=["IMPERSONATION_SENDER_MISMATCH"], why="Single strong signal; shows limited evidence is reported honestly."),
]
